### ISSUE TITLE
deploy app command in AKS-Security README.MD not working

### ISSUE THREAD

**Issue by roberts2727** [ACloudGuru-Resources/az-500#2]
deploy app to AKS
kubectl apply -f cloud-vote.yaml

produces error:

 kubectl apply -f cloud-vote.yaml
service/azure-vote-back created
service/azure-vote-front created
unable to recognize "cloud-vote.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "cloud-vote.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

**Comment by pershoot** [comment]
Please amend accordingly:
diff --git a/aks-security/cloud-vote.yaml b/aks-security/cloud-vote.yaml
index 7d2d8cb..f2eced7 100644
--- a/aks-security/cloud-vote.yaml
+++ b/aks-security/cloud-vote.yaml
@@ -1,9 +1,12 @@
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-back
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-back
   template:
     metadata:
       labels:
@@ -28,12 +31,15 @@ spec:
   selector:
     app: azure-vote-back
 ---
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-front
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-front
   strategy:
     rollingUpdate:
       maxSurge: 1

**Comment by pershoot** [comment]
`diff --git a/aks-security/cloud-vote.yaml b/aks-security/cloud-vote.yaml
index 7d2d8cb..f2eced7 100644
--- a/aks-security/cloud-vote.yaml
+++ b/aks-security/cloud-vote.yaml
@@ -1,9 +1,12 @@
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-back
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-back
   template:
     metadata:
       labels:
@@ -28,12 +31,15 @@ spec:
   selector:
     app: azure-vote-back
 ---
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-front
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-front
   strategy:
     rollingUpdate:
       maxSurge: 1`

**Comment by pershoot** [comment]
Please amend accordingly:
diff --git a/aks-security/cloud-vote.yaml b/aks-security/cloud-vote.yaml
index 7d2d8cb..f2eced7 100644
--- a/aks-security/cloud-vote.yaml
+++ b/aks-security/cloud-vote.yaml
@@ -1,9 +1,12 @@
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-back
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-back
   template:
     metadata:
       labels:
@@ -28,12 +31,15 @@ spec:
   selector:
     app: azure-vote-back
 ---
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-front
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-front
   strategy:
     rollingUpdate:
       maxSurge: `1```

**Comment by pershoot** [comment]
Please amend accordingly:

diff --git a/aks-security/cloud-vote.yaml b/aks-security/cloud-vote.yaml
index 7d2d8cb..f2eced7 100644
--- a/aks-security/cloud-vote.yaml
+++ b/aks-security/cloud-vote.yaml
@@ -1,9 +1,12 @@
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-back
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-back
   template:
     metadata:
       labels:
@@ -28,12 +31,15 @@ spec:
   selector:
     app: azure-vote-back
 ---
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: azure-vote-front
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: azure-vote-front
   strategy:
     rollingUpdate:
       maxSurge: 1

**Comment by roberts2727** [comment]
> Please amend accordingly:
> 
> diff --git a/aks-security/cloud-vote.yaml b/aks-security/cloud-vote.yaml
> index 7d2d8cb..f2eced7 100644
> --- a/aks-security/cloud-vote.yaml
> +++ b/aks-security/cloud-vote.yaml
> @@ -1,9 +1,12 @@
> -apiVersion: apps/v1beta1
> +apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: azure-vote-back
> spec:
> replicas: 1
> 
> * selector:
> * matchLabels:
> * ```
>    app: azure-vote-back
>   ```
>   
>   
>   template:
>   metadata:
>   labels:
>   @@ -28,12 +31,15 @@ spec:
>   selector:
>   app: azure-vote-back
> 
> -apiVersion: apps/v1beta1
> +apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: azure-vote-front
> spec:
> replicas: 1
> 
> * selector:
> * matchLabels:
> * ```
>    app: azure-vote-front
>   ```
>   
>   
>   strategy:
>   rollingUpdate:
>   maxSurge: 1

Sorry, not an expert at interperting github diffs, could you update the example, or paste the code in here?

**Comment by pershoot** [comment]
Change this: apiVersion: apps/v1beta1 to this: apiVersion: apps/v1 (above kind: Deployment).

Then add selector to azure-vote-back/front accordingly:

For azure-vote-back and azure-vote-front, after: replicas: 1, add:
   selector:
     matchLabels:
       app: azure-vote-back

...

   selector:
     matchLabels:
       app: azure-vote-front

**Comment by pershoot** [comment]
http://droidbasement.com/aks-security.diff.txt

**Comment by pershoot** [comment]
https://github.com/pershoot/az-500/commit/e42c0d8e539ffc80907cd658bcc1502d06511d1b

I've created a Pull Request here:
https://github.com/ACloudGuru-Resources/az-500/pull/3

**Comment by roberts2727** [comment]
> [pershoot@e42c0d8](https://github.com/pershoot/az-500/commit/e42c0d8e539ffc80907cd658bcc1502d06511d1b)
> 
> I've created a Pull Request here:
> #3

Thank you so much Sir!
